//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoOn.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GoOnEntities : DbContext
    {
        public GoOnEntities()
            : base("name=GoOnEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<asignatura> asignatura { get; set; }
        public virtual DbSet<carga_academica> carga_academica { get; set; }
        public virtual DbSet<carrera> carrera { get; set; }
        public virtual DbSet<categoria> categoria { get; set; }
        public virtual DbSet<cotidianidad> cotidianidad { get; set; }
        public virtual DbSet<grupos> grupos { get; set; }
        public virtual DbSet<reportes> reportes { get; set; }
        public virtual DbSet<tipo_usuario> tipo_usuario { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    
        public virtual int sp_Crear_Usuario(Nullable<int> rut, string dv, string user, string pass, string nombres, string apellido, string correo, Nullable<int> celular, string captura, Nullable<System.DateTime> fecha, Nullable<int> idCarrera, Nullable<int> idTipoUser)
        {
            var rutParameter = rut.HasValue ?
                new ObjectParameter("rut", rut) :
                new ObjectParameter("rut", typeof(int));
    
            var dvParameter = dv != null ?
                new ObjectParameter("dv", dv) :
                new ObjectParameter("dv", typeof(string));
    
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            var nombresParameter = nombres != null ?
                new ObjectParameter("nombres", nombres) :
                new ObjectParameter("nombres", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("apellido", apellido) :
                new ObjectParameter("apellido", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("correo", correo) :
                new ObjectParameter("correo", typeof(string));
    
            var celularParameter = celular.HasValue ?
                new ObjectParameter("celular", celular) :
                new ObjectParameter("celular", typeof(int));
    
            var capturaParameter = captura != null ?
                new ObjectParameter("captura", captura) :
                new ObjectParameter("captura", typeof(string));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            var idCarreraParameter = idCarrera.HasValue ?
                new ObjectParameter("idCarrera", idCarrera) :
                new ObjectParameter("idCarrera", typeof(int));
    
            var idTipoUserParameter = idTipoUser.HasValue ?
                new ObjectParameter("idTipoUser", idTipoUser) :
                new ObjectParameter("idTipoUser", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Crear_Usuario", rutParameter, dvParameter, userParameter, passParameter, nombresParameter, apellidoParameter, correoParameter, celularParameter, capturaParameter, fechaParameter, idCarreraParameter, idTipoUserParameter);
        }
    }
}
