//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoOn.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.asignatura = new HashSet<asignatura>();
            this.cotidianidad = new HashSet<cotidianidad>();
            this.grupos = new HashSet<grupos>();
            this.reportes = new HashSet<reportes>();
        }
    
        public int rut { get; set; }
        public string dv { get; set; }
        public string username { get; set; }
        public string passwd { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public string correo { get; set; }
        public int celular { get; set; }
        public string foto { get; set; }
        public HttpPostedFileBase imageFile { get; set; }
        public System.DateTime fecha_registro { get; set; }
        public Nullable<int> id_carrera { get; set; }
        public Nullable<int> id_tipouser { get; set; }
        
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<asignatura> asignatura { get; set; }
        public virtual carrera carrera { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cotidianidad> cotidianidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<grupos> grupos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reportes> reportes { get; set; } 
        public virtual tipo_usuario tipo_usuario { get; set; }
    }
}
