//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class categoria
    {
        public int id_categoria { get; set; }
        public Nullable<int> id_carga_acad { get; set; }
        public Nullable<int> id_cotidianidad { get; set; }
    
        public virtual carga_academica carga_academica { get; set; }
        public virtual cotidianidad cotidianidad { get; set; }
    }
}
