//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class grupos
    {
        public int id_grupo { get; set; }
        public string nombre_grupo { get; set; }
        public int id_usuario { get; set; }
        public bool administrador { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
