//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class reportes
    {
        public int id_reporte { get; set; }
        public System.DateTime fecha { get; set; }
        public string decripcion { get; set; }
        public Nullable<int> id_user { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
